### ISSUE TITLE
unknown color code "reset" (&r)

### ISSUE THREAD

**Issue by skyrawr** [PorkStudios/Pork2b2tBot#38]
[03/05/2020 15:44:01] [INFO] Starting Pork2b2tBot v0.2.5...
[03/05/2020 15:44:01] [WebSocket] [INFO] Starting WebSocket server...
[03/05/2020 15:44:01] [Module] [TRACE] Enabling AntiAFK
[03/05/2020 15:44:01] [Module] [TRACE] Enabling spammer with 1000 messages, choosing every 60 seconds
[03/05/2020 15:44:01] [Auth] [INFO] Logging in...
[03/05/2020 15:44:02] [WebSocket] [SUCCESS] WebSocket server started!
[03/05/2020 15:44:03] [Auth] [SUCCESS] Logged in.
[03/05/2020 15:44:03] [Server] [INFO] Starting server on 0.0.0.0:25565...
[03/05/2020 15:44:04] [Cache] [DEBUG] Clearing cache...
[03/05/2020 15:44:04] [Cache] [DEBUG] Cache cleared.
[03/05/2020 15:44:04] [Server] [SUCCESS] Server started.
[03/05/2020 15:44:04] [Auth] [INFO] Logging in...
[03/05/2020 15:44:04] [Auth] [SUCCESS] Logged in.
[03/05/2020 15:44:04] [Client] [INFO] Connecting to play.gamster.org:25565...
[03/05/2020 15:44:05] [Client] [SUCCESS] Connected to play.gamster.org/54.36.3.231:25565!
[03/05/2020 15:44:05] [INFO] Saving config...
[03/05/2020 15:44:05] [INFO] Config saved.
[03/05/2020 15:44:05] [Chat] [INFO] §7(§3!§7) §fTe conectezi pe §b§lLobby3§f...
[03/05/2020 15:44:05] [Client] [ALERT] ****************************************
[03/05/2020 15:44:05] [Client] [ALERT] * 
[03/05/2020 15:44:05] [Client] [ALERT] * 
java.lang.IllegalArgumentException: Unknown color code: "reset"
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.getColor(JsonTextParser.java:121)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.doParseJson(JsonTextParser.java:82)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.doParseJson(JsonTextParser.java:95)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.doParseJson(JsonTextParser.java:95)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.parse(JsonTextParser.java:63)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.MinecraftFormatParser.parse(MinecraftFormatParser.java:71)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.MinecraftFormatParser.parse(MinecraftFormatParser.java:41)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.logging.impl.SimpleLogger.doLog(SimpleLogger.java:90)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.logging.impl.SimpleLogger$ChannelLogger.log(SimpleLogger.java:143)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.logging.Logger.info(Logger.java:102)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.toobeetooteebot.client.handler.incoming.ChatHandler.apply(ChatHandler.java:35)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.toobeetooteebot.client.handler.incoming.ChatHandler.apply(ChatHandler.java:30)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.toobeetooteebot.util.handler.HandlerRegistry.handleInbound(HandlerRegistry.java:61)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.toobeetooteebot.client.ClientListener.packetReceived(ClientListener.java:52)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:343)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at java.lang.Thread.run(Unknown Source)
[03/05/2020 15:44:05] [Client] [ALERT] * 
[03/05/2020 15:44:05] [Client] [ALERT] ****************************************
[03/05/2020 15:44:05] [Client] [INFO] Disconnecting from server...
[03/05/2020 15:44:05] [Client] [TRACE] Disconnect reason: java.lang.IllegalArgumentException: Unknown color code: "reset"
[03/05/2020 15:44:05] [Client] [INFO] Disconnected.
[03/05/2020 15:44:05] [Client] [ALERT] ****************************************
[03/05/2020 15:44:05] [Client] [ALERT] * 
[03/05/2020 15:44:05] [Client] [ALERT] * 
java.lang.IllegalArgumentException: Unknown color code: "reset"
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.getColor(JsonTextParser.java:121)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.doParseJson(JsonTextParser.java:82)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.doParseJson(JsonTextParser.java:95)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.doParseJson(JsonTextParser.java:95)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.parse(JsonTextParser.java:63)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.MinecraftFormatParser.parse(MinecraftFormatParser.java:71)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.MinecraftFormatParser.parse(MinecraftFormatParser.java:41)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.logging.impl.SimpleLogger.doLog(SimpleLogger.java:90)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.logging.impl.SimpleLogger$ChannelLogger.log(SimpleLogger.java:143)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.lib.logging.Logger.info(Logger.java:102)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.toobeetooteebot.client.handler.incoming.ChatHandler.apply(ChatHandler.java:35)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.toobeetooteebot.client.handler.incoming.ChatHandler.apply(ChatHandler.java:30)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.toobeetooteebot.util.handler.HandlerRegistry.handleInbound(HandlerRegistry.java:61)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at net.daporkchop.toobeetooteebot.client.ClientListener.packetReceived(ClientListener.java:52)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:343)
[03/05/2020 15:44:05] [Client] [ALERT] * 
    at java.lang.Thread.run(Unknown Source)
[03/05/2020 15:44:05] [Client] [ALERT] * 
[03/05/2020 15:44:05] [Client] [ALERT] ****************************************
[03/05/2020 15:44:05] [ALERT] ****************************************
[03/05/2020 15:44:05] [ALERT] * 
[03/05/2020 15:44:05] [ALERT] * 
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unknown color code: "reset"
[03/05/2020 15:44:05] [ALERT] * 
    at java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
[03/05/2020 15:44:05] [ALERT] * 
    at java.util.concurrent.CompletableFuture.get(Unknown Source)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.toobeetooteebot.client.PorkClientSession.getDisconnectReason(PorkClientSession.java:52)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.toobeetooteebot.Bot.start(Bot.java:220)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.toobeetooteebot.Bot.main(Bot.java:98)
[03/05/2020 15:44:05] [ALERT] * 
Caused by: java.lang.IllegalArgumentException: Unknown color code: "reset"
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.getColor(JsonTextParser.java:121)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.doParseJson(JsonTextParser.java:82)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.doParseJson(JsonTextParser.java:95)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.doParseJson(JsonTextParser.java:95)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.JsonTextParser.parse(JsonTextParser.java:63)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.MinecraftFormatParser.parse(MinecraftFormatParser.java:71)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.lib.minecraft.text.parser.MinecraftFormatParser.parse(MinecraftFormatParser.java:41)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.lib.logging.impl.SimpleLogger.doLog(SimpleLogger.java:90)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.lib.logging.impl.SimpleLogger$ChannelLogger.log(SimpleLogger.java:143)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.lib.logging.Logger.info(Logger.java:102)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.toobeetooteebot.client.handler.incoming.ChatHandler.apply(ChatHandler.java:35)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.toobeetooteebot.client.handler.incoming.ChatHandler.apply(ChatHandler.java:30)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.toobeetooteebot.util.handler.HandlerRegistry.handleInbound(HandlerRegistry.java:61)
[03/05/2020 15:44:05] [ALERT] * 
    at net.daporkchop.toobeetooteebot.client.ClientListener.packetReceived(ClientListener.java:52)
[03/05/2020 15:44:05] [ALERT] * 
    at com.github.steveice10.packetlib.event.session.PacketReceivedEvent.call(PacketReceivedEvent.java:51)
[03/05/2020 15:44:05] [ALERT] * 
    at com.github.steveice10.packetlib.tcp.TcpSession.callEvent(TcpSession.java:143)
[03/05/2020 15:44:05] [ALERT] * 
    at com.github.steveice10.packetlib.tcp.TcpSession$3.run(TcpSession.java:343)
[03/05/2020 15:44:05] [ALERT] * 
    at java.lang.Thread.run(Unknown Source)
[03/05/2020 15:44:05] [ALERT] * 
[03/05/2020 15:44:05] [ALERT] ****************************************
[03/05/2020 15:44:05] [INFO] Shutting down...
[03/05/2020 15:44:05] [Server] [INFO] Closing server...
[03/05/2020 15:44:05] [Server] [SUCCESS] Server closed.
[03/05/2020 15:44:07] [WebSocket] [INFO] Shutting down...
[03/05/2020 15:44:07] [WebSocket] [SUCCESS] Shut down.
[03/05/2020 15:44:07] [INFO] Saving config...
[03/05/2020 15:44:07] [INFO] Config saved.

**Comment by DaMatrix** [comment]
Issue has been fixed upstream in PorkLib, I'll update the bot to use the fixed version in a moment.

**Comment by DaMatrix** [comment]
Fixed in 04aab3003952874712fbcb9ed4dd1ef4c97280d7, jar is available [here](https://jenkins.daporkchop.net/job/PorkStudios/job/Pork2b2tBot/job/master/lastSuccessfulBuild/artifact/build/libs/)
